/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectuas2;

/**
 *
 * @author ASus
 */
public class KAMUsAKU extends javax.swing.JFrame {

    /**
     * Creates new form KAMUsAKU
     */
    public KAMUsAKU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbdari = new javax.swing.JComboBox<>();
        cmbke = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txfmasukan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfkeluaran = new javax.swing.JTextField();
        btcari = new javax.swing.JButton();
        btbersih = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dari");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 103, 70, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Ke");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 145, 70, 14);

        cmbdari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bahasa Indonesia", "Bahasa Arab" }));
        cmbdari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbdariActionPerformed(evt);
            }
        });
        getContentPane().add(cmbdari);
        cmbdari.setBounds(80, 100, 170, 20);

        cmbke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bahasa Arab", "Bahasa Indonesia" }));
        cmbke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbke);
        cmbke.setBounds(80, 140, 170, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Masukkan kata yang ingin dicari artinya:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 190, 250, 14);
        getContentPane().add(txfmasukan);
        txfmasukan.setBounds(27, 215, 222, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Hasilnya:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(281, 190, 220, 14);
        getContentPane().add(txfkeluaran);
        txfkeluaran.setBounds(281, 215, 222, 30);

        btcari.setText("Cari Arti");
        btcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcariActionPerformed(evt);
            }
        });
        getContentPane().add(btcari);
        btcari.setBounds(307, 99, 89, 73);

        btbersih.setText("Bersihkan");
        btbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbersihActionPerformed(evt);
            }
        });
        getContentPane().add(btbersih);
        btbersih.setBounds(414, 99, 89, 73);

        jLabel7.setFont(new java.awt.Font("Wilderness", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("KAMUsAKU");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 530, 50);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sebuah aplikasi untuk mencari arti dari rasa ingin tahu yang terus mengikuti.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 40, 530, 14);

        jLabel6.setFont(new java.awt.Font("Vrinda", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kreator: Aditya Rizky Pratama - NIM: H1051191055");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 280, 530, 17);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectuas2/images/3EF3E820-2296-4367-A78F-19DBE12E3BC0 (1) - Copy.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -140, 580, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        cmbdari.addItem("Bahasa Indonesia");
        cmbdari.addItem("Bahasa Arab");
    }
    
    private void cmbdariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbdariActionPerformed
        // TODO add your handling code here:
        String j=(String) cmbdari.getSelectedItem();
        if (j.equals("Bahasa Indonesia")) {
              cmbke.removeAllItems();
            cmbke.addItem("Bahasa Arab");
        }
        if (j.equals("Bahasa Arab")) {
            cmbke.removeAllItems();
            cmbke.addItem("Bahasa Indonesia");
        }
    }//GEN-LAST:event_cmbdariActionPerformed

    private void btcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcariActionPerformed
        // TODO add your handling code here:
        String dari = (String) cmbdari.getSelectedItem();
        String ke = (String) cmbke.getSelectedItem();
        int x = 0, y = 0;
        
        if (dari.equals("Bahasa Indonesia")) {
            x=0;
        }
        if (dari.equals("Bahasa Arab")) {
            x=1;
        }
        if (ke.equals("Bahasa Indonesia")) {
            y=0;
        }
        if (ke.equals("Bahasa Arab")) {
            y=1;
        }
        
        int k,i;k=-1;
        String [] [] kata=new String [101][101];
        
        kata [0][0]="satu";
        kata [0][1]="waahidun";
        kata [1][0]="dua";
        kata [1][1]="itsnaani";
        kata [2][0]="tiga";
        kata [2][1]="tsalaatsatun";
        kata [3][0]="empat";
        kata [3][1]="arba'atun";
        kata [4][0]="lima";
        kata [4][1]="khamsatun";
        kata [5][0]="enam";
        kata [5][1]="sittatun";
        kata [6][0]="tujuh";
        kata [6][1]="sab'atun";
        kata [7][0]="delapan";
        kata [7][1]="tsamaaniyatun";
        kata [8][0]="sembilan";
        kata [8][1]="tis'atun";
        kata [9][0]="sepuluh";
        kata [9][1]="'asyratun";
        kata [10][0]="aku";
        kata [10][1]="ana";
        kata [11][0]="kamu";
        kata [11][1]="anta";
        kata [12][0]="kami";
        kata [12][1]="nahnu";
        kata [13][0]="dia";
        kata [13][1]="huwa";
        kata [14][0]="mereka";
        kata [14][1]="hum";
        kata [15][0]="bahagia";
        kata [15][1]="saidah";
        kata [16][0]="cinta";
        kata [16][1]="hubbu";
        kata [17][0]="marah";
        kata [17][1]="ghadib";
        kata [18][0]="maaf";
        kata [18][1]="asif";
        kata [19][0]="ayah";
        kata [19][1]="abun";
        kata [20][0]="ibu";
        kata [20][1]="ummun";
        kata [21][0]="adik";
        kata [21][1]="akhunshogiir";
        kata [22][0]="kakak";
        kata [22][1]="ukhtunkabiirah";
        kata [23][0]="abang";
        kata [23][1]="akhunkabiir";
        kata [24][0]="keluarga";
        kata [24][1]="usrah";
        kata [25][0]="hari";
        kata [25][1]="yaum";
        kata [26][0]="minggu";
        kata [26][1]="ahad";
        kata [27][0]="senin";
        kata [27][1]="itsnaini";
        kata [28][0]="selasa";
        kata [28][1]="tstsalaatsaa";
        kata [29][0]="rabu";
        kata [29][1]="arbi'aa";
        kata [30][0]="kamis";
        kata [30][1]="khamiis";
        kata [31][0]="jum'at";
        kata [31][1]="jum'ah";
        kata [32][0]="sabtu";
        kata [32][1]="ssabtu";
        kata [33][0]="pagi";
        kata [33][1]="shabaah";
        kata [34][0]="siang";
        kata [34][1]="nahaar";
        kata [35][0]="sore";
        kata [35][1]="masaa";
        kata [36][0]="malam";
        kata [36][1]="lail";
        kata [37][0]="waktu";
        kata [37][1]="waqtun";
        kata [38][0]="bulan";
        kata [38][1]="syahr";
        kata [39][0]="januari";
        kata [39][1]="yanaayir";
        kata [40][0]="februari";
        kata [40][1]="fabraayir";
        kata [41][0]="maret";
        kata [41][1]="maaris";
        kata [42][0]="april";
        kata [42][1]="abriil";
        kata [43][0]="mei";
        kata [43][1]="mayuu";
        kata [44][0]="juni";
        kata [44][1]="yuuniyuu";
        kata [45][0]="juli";
        kata [45][1]="yuuliyuu";
        kata [46][0]="agustus";
        kata [46][1]="aghusthus";
        kata [47][0]="september";
        kata [47][1]="sibtimbar";
        kata [48][0]="oktober";
        kata [48][1]="uktuubar";
        kata [49][0]="november";
        kata [49][1]="nuufambar";
        kata [50][0]="desember";
        kata [50][1]="diisambar";
        kata [51][0]="arah";
        kata [51][1]="jihah";
        kata [52][0]="timur";
        kata [52][1]="asysyarq";
        kata [53][0]="barat";
        kata [53][1]="algharb";
        kata [54][0]="selatan";
        kata [54][1]="asysyamaal";
        kata [55][0]="utara";
        kata [55][1]="aljanuub";
        kata [56][0]="semesta";
        kata [56][1]="alkaun";
        kata [57][0]="bumi";
        kata [57][1]="ardh";
        kata [58][0]="angin";
        kata [58][1]="riih";
        kata [59][0]="gunung";
        kata [59][1]="jabal";
        kata [60][0]="matahari";
        kata [60][1]="syams";
        kata [61][0]="laut";
        kata [61][1]="bahr";
        kata [62][0]="bulan";
        kata [62][1]="qamar";
        kata [63][0]="bintang";
        kata [63][1]="najm";
        kata [64][0]="hujan";
        kata [64][1]="mathar";
        kata [65][0]="awan";
        kata [65][1]="sahaab";
        kata [66][0]="kepala";
        kata [66][1]="ra'sun";
        kata [67][0]="rambut";
        kata [67][1]="sya'run";
        kata [68][0]="telinga";
        kata [68][1]="udzunun";
        kata [69][0]="pipi";
        kata [69][1]="khaddun";
        kata [70][0]="hidung";
        kata [70][1]="anfun";
        kata [71][0]="mulut";
        kata [71][1]="famun";
        kata [72][0]="gigi";
        kata [72][1]="sinnun";
        kata [73][0]="mata";
        kata [73][1]="'ainun";
        kata [74][0]="dahi";
        kata [74][1]="jabhatun";
        kata [75][0]="alis";
        kata [75][1]="haajibun";
        kata [76][0]="leher";
        kata [76][1]="'unuqun";
        kata [77][0]="lidah";
        kata [77][1]="lisaanun";
        kata [78][0]="pakaian";
        kata [78][1]="libaasun";
        kata [79][0]="celana";
        kata [79][1]="sirwaal";
        kata [80][0]="topi";
        kata [80][1]="qubba'ah";
        kata [81][0]="sepatu";
        kata [81][1]="hidaa";
        kata [82][0]="arsitek";
        kata [82][1]="muhandis";
        kata [83][0]="dokter";
        kata [83][1]="duktuurun";
        kata [84][0]="polisi";
        kata [84][1]="buliisun";
        kata [85][0]="tentara";
        kata [85][1]="jundun";
        kata [86][0]="guru";
        kata [86][1]="mudarrits";
        kata [87][0]="pelajar";
        kata [87][1]="thaalib";
        kata [88][0]="rumah";
        kata [88][1]="baitu";
        kata [89][0]="lebah";
        kata [89][1]="nahlun";
        kata [90][0]="semut";
        kata [90][1]="namlun";
        kata [91][0]="ulat";
        kata [91][1]="duudun";
        kata [92][0]="lalat";
        kata [92][1]="dzubaabun";
        kata [93][0]="labalaba";
        kata [93][1]="'ankabuutun";
        kata [94][0]="nyamuk";
        kata [94][1]="ba'uudun";
        kata [95][0]="singa";
        kata [95][1]="asadu";
        kata [96][0]="harimau";
        kata [96][1]="namirun";
        kata [97][0]="gajah";
        kata [97][1]="fiilun";
        kata [98][0]="sapi";
        kata [98][1]="baqarun";
        kata [99][0]="babi";
        kata [99][1]="khinziirun";
        kata [100][0]="kucing";
        kata [100][1]="qiththun";
        
        
        
        String dicari=txfmasukan.getText();
        for(i=0;i<101;i++)
            if (kata[i][x].equalsIgnoreCase(dicari))
                k=i ;
        if (k==-1)
            txfkeluaran.setText("Kata belum ada");
        else
            txfkeluaran.setText(kata[k][y]);
    }//GEN-LAST:event_btcariActionPerformed

    private void cmbkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkeActionPerformed

    private void btbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbersihActionPerformed
        // TODO add your handling code here:
        txfmasukan.setText("");
        txfkeluaran.setText("");
    }//GEN-LAST:event_btbersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KAMUsAKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KAMUsAKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KAMUsAKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KAMUsAKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KAMUsAKU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbersih;
    private javax.swing.JButton btcari;
    private javax.swing.JComboBox<String> cmbdari;
    private javax.swing.JComboBox<String> cmbke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txfkeluaran;
    private javax.swing.JTextField txfmasukan;
    // End of variables declaration//GEN-END:variables
}
